In [1]:
import sys
sys.path.insert(0, "/Users/andreacaliandro/PycharmProjects/hackerrank")

In [3]:
from read_files import read_file, json_like_input

data = read_file('/Users/andreacaliandro/PycharmProjects/hackerrank/CraigslistPostClassifier/data/training.json')
train_df = json_like_input(data)
train_df.head()

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>category</th>
      <th>city</th>
      <th>heading</th>
      <th>section</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>cell-phones</td>
      <td>newyork</td>
      <td>New batteries C-S2 for Blackberry 7100/7130/87...</td>
      <td>for-sale</td>
    </tr>
    <tr>
      <th>1</th>
      <td>cell-phones</td>
      <td>newyork</td>
      <td>*******   Brand New Original SAMSUNG GALAXY NO...</td>
      <td>for-sale</td>
    </tr>
    <tr>
      <th>2</th>
      <td>cell-phones</td>
      <td>newyork</td>
      <td>SAMSUNG GALAXY SIII T-999 MARBLE WHITE T-MOBIL...</td>
      <td>for-sale</td>
    </tr>
    <tr>
      <th>3</th>
      <td>cell-phones</td>
      <td>newyork</td>
      <td>Ipad mini 64gb 4g any sim unlock</td>
      <td>for-sale</td>
    </tr>
    <tr>
      <th>4</th>
      <td>cell-phones</td>
      <td>newyork</td>
      <td>htc evo 4g lte for trade</td>
      <td>for-sale</td>
    </tr>
  </tbody>
</table>
</div>

In [77]:
for section in train_df['section'].unique():
    print section

for-sale
housing
community
services


In [93]:
import pandas as pd
df = pd.DataFrame()
df['l'] = [1,2,3,4,5]
df['a'] = [1,2,3,7,5]
(df['l'] == df['a'])
len(df['l'])

5

In [87]:
train_df.loc[train_df['section']=='housing', 'new_col'] = 5566*['good']
train_df

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>category</th>
      <th>city</th>
      <th>heading</th>
      <th>section</th>
      <th>new_col</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>cell-phones</td>
      <td>newyork</td>
      <td>New batteries C-S2 for Blackberry 7100/7130/87...</td>
      <td>for-sale</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1</th>
      <td>cell-phones</td>
      <td>newyork</td>
      <td>*******   Brand New Original SAMSUNG GALAXY NO...</td>
      <td>for-sale</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>2</th>
      <td>cell-phones</td>
      <td>newyork</td>
      <td>SAMSUNG GALAXY SIII T-999 MARBLE WHITE T-MOBIL...</td>
      <td>for-sale</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3</th>
      <td>cell-phones</td>
      <td>newyork</td>
      <td>Ipad mini 64gb 4g any sim unlock</td>
      <td>for-sale</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4</th>
      <td>cell-phones</td>
      <td>newyork</td>
      <td>htc evo 4g lte for trade</td>
      <td>for-sale</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>5</th>
      <td>cell-phones</td>
      <td>newyork</td>
      <td>Iphone T-mobile Unlock Phone New</td>
      <td>for-sale</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>6</th>
      <td>cell-phones</td>
      <td>newyork</td>
      <td>map</td>
      <td>for-sale</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>7</th>
      <td>cell-phones</td>
      <td>newyork</td>
      <td>at&amp;amp;t iphone 5 32gb black good condition no...</td>
      <td>for-sale</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>8</th>
      <td>cell-phones</td>
      <td>newyork</td>
      <td>iphone 5 white from Tmobile with lifeproof case</td>
      <td>for-sale</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>9</th>
      <td>cell-phones</td>
      <td>newyork</td>
      <td>I-phone 4</td>
      <td>for-sale</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>10</th>
      <td>cell-phones</td>
      <td>newyork</td>
      <td>I PHONE 4</td>
      <td>for-sale</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>11</th>
      <td>cell-phones</td>
      <td>newyork</td>
      <td>LG Spectrum 2 Shell Holster Case</td>
      <td>for-sale</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>12</th>
      <td>cell-phones</td>
      <td>newyork</td>
      <td>OtterBox Defender Case for iPhone 4S</td>
      <td>for-sale</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>13</th>
      <td>cell-phones</td>
      <td>newyork</td>
      <td>factory Unlocked iphone 5 16gb</td>
      <td>for-sale</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>14</th>
      <td>cell-phones</td>
      <td>newyork</td>
      <td>Samsung Galaxy S3 16G</td>
      <td>for-sale</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>15</th>
      <td>cell-phones</td>
      <td>newyork</td>
      <td>iphone 5 white 16 gb at&amp;amp;t Factory unlocked...</td>
      <td>for-sale</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>16</th>
      <td>cell-phones</td>
      <td>newyork</td>
      <td>Unlocked Blackberry Bold 9900</td>
      <td>for-sale</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>17</th>
      <td>cell-phones</td>
      <td>newyork</td>
      <td>iPhone 5 tmobile 32gb black 10-10</td>
      <td>for-sale</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>18</th>
      <td>cell-phones</td>
      <td>newyork</td>
      <td>ALL Samsung PHONES Unlock &amp;amp; IMEI Fix Service</td>
      <td>for-sale</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>19</th>
      <td>cell-phones</td>
      <td>newyork</td>
      <td>ALL Samsung PHONES  Unlock &amp;amp; IMEI Fix Service</td>
      <td>for-sale</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>20</th>
      <td>cell-phones</td>
      <td>newyork</td>
      <td>i want to buy ipad 4,wifi,4g,mini,iphone 5/4/4...</td>
    

In [11]:
train_df.groupby('city').count

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>category</th>
      <th>heading</th>
      <th>section</th>
    </tr>
    <tr>
      <th>city</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>bangalore</th>
      <td>585</td>
      <td>585</td>
      <td>585</td>
    </tr>
    <tr>
      <th>chicago</th>
      <td>4469</td>
      <td>4469</td>
      <td>4469</td>
    </tr>
    <tr>
      <th>delhi</th>
      <td>216</td>
      <td>216</td>
      <td>216</td>
    </tr>
    <tr>
      <th>dubai.en</th>
      <td>454</td>
      <td>454</td>
      <td>454</td>
    </tr>
    <tr>
      <th>frankfurt.en</th>
      <td>4</td>
      <td>4</td>
      <td>4</td>
    </tr>
    <tr>
      <th>geneva.en</th>
      <td>5</td>
      <td>5</td>
      <td>5</td>
    </tr>
    <tr>
      <th>hyderabad</th>
      <td>260</td>
      <td>260</td>
      <td>260</td>
    </tr>
    <tr>
      <th>kolkata.en</th>
      <td>5</td>
      <td>5</td>
      <td>5</td>
    </tr>
    <tr>
      <th>london</th>
      <td>1663</td>
      <td>1663</td>
      <td>1663</td>
    </tr>
    <tr>
      <th>manchester</th>
      <td>7</td>
      <td>7</td>
      <td>7</td>
    </tr>
    <tr>
      <th>mumbai</th>
      <td>273</td>
      <td>273</td>
      <td>273</td>
    </tr>
    <tr>
      <th>newyork</th>
      <td>5625</td>
      <td>5625</td>
      <td>5625</td>
    </tr>
    <tr>
      <th>paris.en</th>
      <td>774</td>
      <td>774</td>
      <td>774</td>
    </tr>
    <tr>
      <th>seattle</th>
      <td>4118</td>
      <td>4118</td>
      <td>4118</td>
    </tr>
    <tr>
      <th>singapore</th>
      <td>1756</td>
      <td>1756</td>
      <td>1756</td>
    </tr>
    <tr>
      <th>zurich.en</th>
      <td>3</td>
      <td>3</td>
      <td>3</td>
    </tr>
  </tbody>
</table>
</div>

In [46]:
train_df['heading'][0]

u'New batteries C-S2 for Blackberry 7100/7130/8700/Curve/Pearl'

In [44]:
from sklearn.feature_extraction.text import TfidfVectorizer
v = TfidfVectorizer()
x = v.fit_transform(train_df['heading'][:10])

## Example to familiarize 

In [48]:
docs = ['Luca e Emma','LUCA non mangia','EMMA Non dorme']
x = v.fit_transform(docs)

In [50]:
x.toarray()

array([[ 0.        ,  0.70710678,  0.70710678,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.51785612,  0.68091856,  0.51785612],
       [ 0.68091856,  0.51785612,  0.        ,  0.        ,  0.51785612]])

In [73]:
x_find = np.array([(1./3)*(np.log(4./3)+1), (1./3)*(np.log(4./2)+1), (1./3)*(np.log(4./3)+1)])
x_find/np.sqrt((x_find**2).sum())

array([ 0.51785612,  0.68091856,  0.51785612])

In [68]:
v.get_feature_names()

[u'dorme', u'emma', u'luca', u'mangia', u'non']

In [69]:
test_docs = ['Emma mangia', 'Luca dorme']
y = v.transform(test_docs)

In [71]:
y.toarray()

array([[ 0.        ,  0.60534851,  0.        ,  0.79596054,  0.        ],
       [ 0.79596054,  0.        ,  0.60534851,  0.        ,  0.        ]])

In [74]:
y_find = np.array([(1./2)*(np.log(4./3)+1), (1./2)*(np.log(4./2)+1)])
y_find/np.sqrt((y_find**2).sum())

array([ 0.60534851,  0.79596054])

`v.transform(test_docs)` calculates the tf of each word according to the actual doc, while the idf is given by the training_doc sample.